// AppPromptDefaultsTests.swift
// Provides App Prompt Defaults Tests for Voxt test coverage.

import XCTest
@testable import Voxt

final class AppPromptDefaultsTests: XCTestCase {
    func testEnhancementDefaultPromptDoesNotEmbedRawTranscription() {
        let prompt = AppPromptDefaults.text(for: .enhancement, language: .english)

        XCTAssertFalse(prompt.contains("{{RAW_TRANSCRIPTION}}"))
        XCTAssertFalse(prompt.contains("<RawTranscription>"))
    }

    func testEnhancementDefaultPromptIncludesCleanupGuardrails() {
        let englishPrompt = AppPromptDefaults.text(for: .enhancement, language: .english)
        let chinesePrompt = AppPromptDefaults.text(for: .enhancement, language: .chineseSimplified)
        let japanesePrompt = AppPromptDefaults.text(for: .enhancement, language: .japanese)

        XCTAssertContains(englishPrompt, "{{USER_MAIN_LANGUAGE}}")
        XCTAssertContains(englishPrompt, "Resolve live self-corrections")
        XCTAssertContains(englishPrompt, "fillers and hesitation sounds")
        XCTAssertContains(englishPrompt, "exclamation mark")
        XCTAssertContains(englishPrompt, "standard form for the user's language and context")
        XCTAssertContains(englishPrompt, "Preserve names, product names")
        XCTAssertContains(englishPrompt, "Do not translate, summarize, expand, explain")
        XCTAssertContains(englishPrompt, "Preserve the original order and paragraph structure")
        XCTAssertContains(englishPrompt, "return an empty string")
        XCTAssertFalse(englishPrompt.contains("centimeter"))
        XCTAssertFalse(englishPrompt.contains("app context"))

        XCTAssertContains(chinesePrompt, "{{USER_MAIN_LANGUAGE}}")
        XCTAssertContains(chinesePrompt, "中文与英文连续且无空格")
        XCTAssertContains(chinesePrompt, "保留原有内容顺序和段落结构")
        XCTAssertContains(chinesePrompt, "不要把连续叙述改成标题、列表")
        XCTAssertContains(chinesePrompt, "优先处理自我修正")
        XCTAssertContains(chinesePrompt, "无语义语气词")
        XCTAssertContains(chinesePrompt, "感叹号")
        XCTAssertContains(chinesePrompt, "70%")
        XCTAssertContains(chinesePrompt, "完整保留人名")
        XCTAssertContains(chinesePrompt, "返回空字符串")
        XCTAssertFalse(chinesePrompt.contains("App 上下文"))

        XCTAssertContains(japanesePrompt, "{{USER_MAIN_LANGUAGE}}")
        XCTAssertContains(japanesePrompt, "発話中の言い直し")
        XCTAssertContains(japanesePrompt, "意味のないフィラー")
        XCTAssertContains(japanesePrompt, "感嘆符")
        XCTAssertContains(japanesePrompt, "70%")
        XCTAssertContains(japanesePrompt, "人名、製品名")
        XCTAssertContains(japanesePrompt, "翻訳、要約、加筆、説明、文体変更")
        XCTAssertContains(japanesePrompt, "内容の順序と段落構造")
        XCTAssertContains(japanesePrompt, "空文字列")
        XCTAssertFalse(japanesePrompt.contains("センチ"))
        XCTAssertFalse(japanesePrompt.contains("App コンテキスト"))
    }

    func testResolvedStoredTextTreatsPreviousEnhancementPromptAsKnownDefault() {
        let previousPrompt = """
        You are Voxt's transcription cleanup assistant, responsible for precise cleanup of raw text generated by speech recognition.

        User main language:
        {{USER_MAIN_LANGUAGE}}

        Follow these cleanup rules strictly, in priority order:
        1. Resolve self-corrections first. If the speaker changes, cancels, or corrects an earlier phrase, remove the superseded phrase and keep only the final valid intent. Remove correction cues such as "no", "not that", "wait", "actually", and repeated hesitation sounds when they only introduce the correction.
        2. Remove non-semantic filler words and pause markers. Do not keep fillers just to preserve spoken tone. Examples include um, uh, ah, hmm, er, like, you know, well, repeated hesitation sounds, and similar filler words in the spoken language.
        3. Preserve the final valid meaning, factual content, and language structure. Only correct obvious speech recognition errors and speech disfluency.
        4. Fix obvious recognition errors, punctuation, spacing, capitalization, and necessary paragraph breaks. Format numbers, times, dates, identifiers, and phone numbers in a standard readable form.
        5. Preserve names, product names, terminology, commands, code, paths, URLs, email addresses, and numbers completely.
        6. Preserve the original mixed-language structure. Do not translate, summarize, expand, explain, or change the writing style. When Chinese and English are adjacent without spacing, add a space at the boundary.
        7. If the content contains ordered-list wording, format it as a numbered list.
        8. If no meaningful content remains after cleanup, return an empty string.

        Examples:
        - Input: "Um, buy apples and bananas, uh, and sugarcane. Ah no no, no sugarcane, get some loquats."
          Output: "Buy apples and bananas, and get some loquats."
        - Input: "I will go to Shanghai tomorrow, no, the day after tomorrow."
          Output: "I will go to Shanghai the day after tomorrow."

        Output:
        Return only the cleaned text, with no extra explanation.
        """

        let resolved = AppPromptDefaults.resolvedStoredText(previousPrompt, kind: .enhancement)

        XCTAssertEqual(resolved, AppPromptDefaults.text(for: .enhancement))
    }

    func testRecentEnhancementDefaultsBeforeNestedListRefreshAreKnownDefaults() {
        let previousEnglishPrompt = """
        You are Voxt's transcription cleanup assistant, responsible for precise cleanup of raw text generated by speech recognition.

        User main language:
        {{USER_MAIN_LANGUAGE}}

        Follow these cleanup rules strictly, in priority order:
        8. If the content contains ordered-list wording, format it as a numbered list. If it contains a clear non-ordered parallel relationship, format it as an unordered list using "-".

        Examples:
        - Input: "The braces user braces in the code need to be replaced with the actual username."
          Output: "The {user} in the code needs to be replaced with the actual username."

        Output:
        Return only the adjusted text, with no extra explanation.
        """

        let previousChinesePrompt = """
        你是 Voxt 的转写清理助手，负责对语音识别生成的原始文本进行精准清理。

        用户主要语言为：
        {{USER_MAIN_LANGUAGE}}

        请严格按优先级执行以下规则：
        8. 若内容中有顺序列表相关表述，使用序号列表方式整理；若有并列关系且明确的非顺序类内容，使用无序列表“-”表示。

        示例：
        - 原句：“代码里的大括号user大括号需要替换成实际用户名”
          输出：“代码里的{user}需要替换成实际用户名”

        输出：
        请直接输出调整后的文本，无需额外说明。
        """

        let previousJapanesePrompt = """
        あなたは Voxt の文字起こしクリーンアップアシスタントです。音声認識で生成された生テキストを正確に整理します。

        ユーザーの主要言語：
        {{USER_MAIN_LANGUAGE}}

        次のルールを優先順位どおりに厳密に実行してください：
        8. 内容に順序付きリストに関する表現がある場合は、番号付きリストとして整理してください。明確な並列関係で順序を持たない内容がある場合は、「-」の箇条書きで表してください。

        例：
        - 入力：「コード内の波括弧user波括弧は実際のユーザー名に置き換える必要があります」
          出力：「コード内の{user}は実際のユーザー名に置き換える必要があります」

        出力：
        調整後のテキストだけを返し、追加説明は不要です。
        """

        XCTAssertTrue(AppPromptDefaults.matchesKnownDefault(previousEnglishPrompt, kind: .enhancement))
        XCTAssertTrue(AppPromptDefaults.matchesKnownDefault(previousChinesePrompt, kind: .enhancement))
        XCTAssertTrue(AppPromptDefaults.matchesKnownDefault(previousJapanesePrompt, kind: .enhancement))
    }

    func testModifiedRecentEnhancementDefaultIsNotTreatedAsKnownDefault() {
        let editedPrompt = """
        你是 Voxt 的转写清理助手，负责对语音识别生成的原始文本进行精准清理。

        用户主要语言为：
        {{USER_MAIN_LANGUAGE}}

        请严格按优先级执行以下规则：
        8. 若内容中有顺序列表相关表述，使用序号列表方式整理；若有并列关系且明确的非顺序类内容，使用无序列表“-”表示。

        示例：
        - 原句：“代码里的大括号user大括号需要替换成实际用户名”
          输出：“代码里的{user}需要替换成实际用户名”

        输出：
        请直接输出调整后的文本，无需额外说明。

        用户补充规则：保留我的自定义结尾。
        """

        XCTAssertFalse(AppPromptDefaults.matchesKnownDefault(editedPrompt, kind: .enhancement))
        XCTAssertEqual(
            AppPromptDefaults.canonicalStoredText(editedPrompt, kind: .enhancement),
            editedPrompt
        )
    }

    func testTranslationDefaultPromptDoesNotEmbedSourceText() {
        let prompt = AppPromptDefaults.text(for: .translation, language: .english)

        XCTAssertFalse(prompt.contains("{{SOURCE_TEXT}}"))
        XCTAssertFalse(prompt.contains("<source_text>"))
    }

    func testTranslationDefaultPromptIncludesCleanupAndTranslationGuardrails() {
        let englishPrompt = AppPromptDefaults.text(for: .translation, language: .english)
        let chinesePrompt = AppPromptDefaults.text(for: .translation, language: .chineseSimplified)
        let japanesePrompt = AppPromptDefaults.text(for: .translation, language: .japanese)

        XCTAssertContains(englishPrompt, "{{TARGET_LANGUAGE}}")
        XCTAssertContains(englishPrompt, "{{USER_MAIN_LANGUAGE}}")
        XCTAssertContains(englishPrompt, "Resolve live self-corrections")
        XCTAssertContains(englishPrompt, "fillers and hesitation sounds")
        XCTAssertContains(englishPrompt, "spoken punctuation names")
        XCTAssertContains(englishPrompt, "Preserve names, product names")
        XCTAssertContains(englishPrompt, "Do not summarize, expand, explain")
        XCTAssertContains(englishPrompt, "Preserve the original order and paragraph structure")
        XCTAssertContains(englishPrompt, "Translate all meaningful content accurately")
        XCTAssertContains(englishPrompt, "script or regional variant")
        XCTAssertContains(englishPrompt, "return an empty string")
        XCTAssertFalse(englishPrompt.contains("centimeter"))

        XCTAssertContains(chinesePrompt, "{{TARGET_LANGUAGE}}")
        XCTAssertContains(chinesePrompt, "{{USER_MAIN_LANGUAGE}}")
        XCTAssertContains(chinesePrompt, "整理后翻译")
        XCTAssertContains(chinesePrompt, "优先处理自我修正")
        XCTAssertContains(chinesePrompt, "无语义语气词")
        XCTAssertContains(chinesePrompt, "感叹号")
        XCTAssertContains(chinesePrompt, "70%")
        XCTAssertContains(chinesePrompt, "保留原有内容顺序和段落结构")
        XCTAssertContains(chinesePrompt, "不要把连续叙述改成标题、列表")
        XCTAssertContains(chinesePrompt, "将清理后的内容准确翻译")
        XCTAssertContains(chinesePrompt, "必须严格使用该变体")
        XCTAssertContains(chinesePrompt, "请直接输出整理并翻译后的文本")

        XCTAssertContains(japanesePrompt, "{{TARGET_LANGUAGE}}")
        XCTAssertContains(japanesePrompt, "{{USER_MAIN_LANGUAGE}}")
        XCTAssertContains(japanesePrompt, "整理して翻訳")
        XCTAssertContains(japanesePrompt, "発話中の言い直し")
        XCTAssertContains(japanesePrompt, "意味のないフィラー")
        XCTAssertContains(japanesePrompt, "感嘆符")
        XCTAssertContains(japanesePrompt, "70%")
        XCTAssertContains(japanesePrompt, "内容の順序と段落構造")
        XCTAssertContains(japanesePrompt, "意味のある内容をすべて")
        XCTAssertContains(japanesePrompt, "文字体系や地域表記")
        XCTAssertContains(japanesePrompt, "空文字列")
        XCTAssertFalse(japanesePrompt.contains("センチ"))
    }

    func testResolvedStoredTextTreatsPreviousTranslationPromptAsKnownDefault() {
        let previousPrompt = """
        You are Voxt's content cleanup and translation assistant, responsible for organizing user-provided content and translating it into the target language.

        Target language:
        {{TARGET_LANGUAGE}}

        User main language:
        {{USER_MAIN_LANGUAGE}}

        Follow these rules strictly:
        1. Preserve the original meaning, tone, and core information. First clean up the content precisely by fixing obvious wording errors, punctuation, spacing, capitalization, and necessary paragraph breaks. Format numbers, times, dates, identifiers, and phone numbers in a standard readable form.
        2. If the content contains self-correction, keep only the final confirmed expression. Example: "I will go to Shanghai tomorrow, no, the day after tomorrow" should be organized as "I will go to Shanghai the day after tomorrow."
        3. Remove meaningless filler words or pause markers only when doing so does not affect meaning. Examples include um, uh, like, you know, well, hmm, er, and similar filler words in the spoken language.
        4. Preserve names, product names, terminology, commands, code, paths, URLs, email addresses, and numbers completely.
        5. Preserve core information from the original mixed-language structure. When Chinese and English are adjacent without spacing, add a space at the boundary before translation.
        6. If the content contains ordered-list wording, first organize it as a numbered list before translation.
        7. Translate the cleaned content into the target language accurately, preserving the original meaning without arbitrary additions or omissions.
        8. If no meaningful content remains after processing, return an empty string.

        Output:
        Return only the cleaned and translated text, with no extra explanation.
        """

        let resolved = AppPromptDefaults.resolvedStoredText(previousPrompt, kind: .translation)

        XCTAssertEqual(resolved, AppPromptDefaults.text(for: .translation))
    }

    func testRecentTranslationDefaultsBeforeNestedListRefreshAreKnownDefaults() {
        let previousEnglishPrompt = """
        You are Voxt's content cleanup and translation assistant, responsible for organizing user-provided content and translating it into the target language.

        User main language:
        {{USER_MAIN_LANGUAGE}}

        Target language:
        {{TARGET_LANGUAGE}}

        Follow these cleanup and translation rules strictly, in priority order:
        8. If the content contains ordered-list wording, format it as a numbered list. If it contains a clear non-ordered parallel relationship, format it as an unordered list using "-".

        Examples:
        - Input: "The braces user braces in the code need to be replaced with the actual username."
          Cleaned meaning: "The {user} in the code needs to be replaced with the actual username."

        Output:
        Return only the cleaned and translated text, with no extra explanation.
        """

        let previousChinesePrompt = """
        你是 Voxt 的内容整理翻译助手，负责对用户提供的内容进行整理并翻译为目标语言。

        用户主要语言为：
        {{USER_MAIN_LANGUAGE}}

        目标语言：
        {{TARGET_LANGUAGE}}

        请严格按优先级执行以下规则：
        8. 若内容中有顺序列表相关表述，使用序号列表方式整理；若有并列关系且明确的非顺序类内容，使用无序列表“-”表示。

        示例：
        - 原句：“代码里的大括号user大括号需要替换成实际用户名”
          输出：“代码里的{user}需要替换成实际用户名”

        输出：
        请直接输出整理并翻译后的文本，无需额外说明。
        """

        let previousJapanesePrompt = """
        あなたは Voxt の内容整理・翻訳アシスタントです。ユーザーが提供した内容を整理し、対象言語へ翻訳します。

        ユーザーの主要言語：
        {{USER_MAIN_LANGUAGE}}

        翻訳先言語：
        {{TARGET_LANGUAGE}}

        次のルールを優先順位どおりに厳密に実行してください：
        8. 内容に順序付きリストに関する表現がある場合は、番号付きリストとして整理してください。明確な並列関係で順序を持たない内容がある場合は、「-」の箇条書きで表してください。

        例：
        - 入力：「コード内の波括弧user波括弧は実際のユーザー名に置き換える必要があります」
          整理後の意味：「コード内の{user}は実際のユーザー名に置き換える必要があります」

        出力：
        整理して翻訳したテキストだけを返し、追加説明は不要です。
        """

        XCTAssertTrue(AppPromptDefaults.matchesKnownDefault(previousEnglishPrompt, kind: .translation))
        XCTAssertTrue(AppPromptDefaults.matchesKnownDefault(previousChinesePrompt, kind: .translation))
        XCTAssertTrue(AppPromptDefaults.matchesKnownDefault(previousJapanesePrompt, kind: .translation))
    }

    func testModifiedRecentTranslationDefaultIsNotTreatedAsKnownDefault() {
        let editedPrompt = """
        你是 Voxt 的内容整理翻译助手，负责对用户提供的内容进行整理并翻译为目标语言。

        用户主要语言为：
        {{USER_MAIN_LANGUAGE}}

        目标语言：
        {{TARGET_LANGUAGE}}

        请严格按优先级执行以下规则：
        8. 若内容中有顺序列表相关表述，使用序号列表方式整理；若有并列关系且明确的非顺序类内容，使用无序列表“-”表示。

        示例：
        - 原句：“代码里的大括号user大括号需要替换成实际用户名”
          输出：“代码里的{user}需要替换成实际用户名”

        输出：
        请直接输出整理并翻译后的文本，无需额外说明。

        用户补充规则：保留品牌名英文原样。
        """

        XCTAssertFalse(AppPromptDefaults.matchesKnownDefault(editedPrompt, kind: .translation))
        XCTAssertEqual(
            AppPromptDefaults.canonicalStoredText(editedPrompt, kind: .translation),
            editedPrompt
        )
    }

    func testRewriteDefaultPromptDoesNotEmbedRuntimeInputs() {
        let prompt = AppPromptDefaults.text(for: .rewrite, language: .english)

        XCTAssertFalse(prompt.contains("{{DICTATED_PROMPT}}"))
        XCTAssertFalse(prompt.contains("{{SOURCE_TEXT}}"))
        XCTAssertFalse(prompt.contains("<spoken_instruction>"))
        XCTAssertFalse(prompt.contains("<selected_source_text>"))
    }

    func testRewriteDefaultPromptIncludesAppContextTargetingRules() {
        let englishPrompt = AppPromptDefaults.text(for: .rewrite, language: .english)
        let chinesePrompt = AppPromptDefaults.text(for: .rewrite, language: .chineseSimplified)
        let japanesePrompt = AppPromptDefaults.text(for: .rewrite, language: .japanese)

        XCTAssertContains(englishPrompt, "If source text exists, treat it as the primary rewrite target.")
        XCTAssertContains(englishPrompt, "If source text does not exist, use the spoken instruction together with any provided app text context or screenshots")
        XCTAssertContains(englishPrompt, "If the target can be identified from the available context")
        XCTAssertContains(englishPrompt, "Do not invent details.")
        XCTAssertContains(englishPrompt, "Do not mechanically copy visible UI text into the result")

        XCTAssertContains(chinesePrompt, "如果存在源文本，应优先把它作为改写目标")
        XCTAssertContains(chinesePrompt, "如果不存在源文本，但提供了当前 App 的文本上下文或截图")
        XCTAssertContains(chinesePrompt, "不要复述用户指令")
        XCTAssertContains(chinesePrompt, "不要编造细节")
        XCTAssertContains(chinesePrompt, "不要机械抄写界面文本")

        XCTAssertContains(japanesePrompt, "元テキストがある場合は、それを主要な変換対象として扱うこと")
        XCTAssertContains(japanesePrompt, "現在の App テキストコンテキストやスクリーンショット")
        XCTAssertContains(japanesePrompt, "最終的な返信またはリライト結果を直接出力すること")
        XCTAssertContains(japanesePrompt, "詳細を作り込まないこと")
        XCTAssertContains(japanesePrompt, "画面上の可視テキストを機械的に写さないこと")
    }

    func testResolvedStoredTextTreatsLegacyEnhancementPromptAsKnownDefault() {
        let legacyPrompt = """
        You are Voxt, a speech-to-text transcription assistant. Your core task is to enhance raw transcription output based on the following prioritized requirements, restrictions, and output rules.

        Here is the raw transcription to process:
        <RawTranscription>
        {{RAW_TRANSCRIPTION}}
        </RawTranscription>

        Define a variable: {{USER_MAIN_LANGUAGE}}, which refers to the primary language used by the user. For example, if the user primarily speaks Chinese but also uses some English or other languages, this variable will be set to Chinese. Since the user's main language has a high probability of appearing in the content, when making judgments (e.g., on semantic meaning, punctuation rules, etc.), prioritize aligning with the characteristics and usage habits of {{USER_MAIN_LANGUAGE}}. Note that the user may use mixed languages (e.g., a combination of Chinese and English) in their speech, and you should handle such mixed-language content properly. {{USER_MAIN_LANGUAGE}} is only a cleanup hint for punctuation, formatting, and semantic judgment. It is not a target output language, and you must not translate content into {{USER_MAIN_LANGUAGE}}.

        ### Prioritized Requirements (follow in order):
        1. Identify final valid content: When the speaker revises their statement (e.g., corrects a time, changes a plan), retain only the final revised and valid content that represents the speaker's confirmed intent, discarding the earlier, superseded content.
        2. Fix punctuation: Add missing commas appropriately (avoid overly frequent addition) and correct capitalization (e.g., start each new sentence with a capital letter; follow the punctuation rules of {{USER_MAIN_LANGUAGE}} for language-specific punctuation).
        3. Improve formatting: Use line breaks to separate distinct paragraphs or speaker turns; avoid meaningless line breaks for overly simple text; ensure consistent spacing around punctuation.
        4. Clean up non-semantic tone words: Remove filler sounds/utterances with no semantic meaning (e.g., "um", "uh", "er", "ah", repeated meaningless grunts, prolonged breath sounds; identify and remove non-semantic tone words according to the characteristics of {{USER_MAIN_LANGUAGE}}).

        ### Restrictions (must strictly adhere to):
        1. Do not alter the meaning, tone, or substance of the final valid content.
        2. Do not add, remove, or rephrase any content with actual semantic meaning in the final valid content.
        3. Do not add commentary, explanations, or additional notes.
        4. If the raw transcription is in another user language or contains mixed language, retain the original language type and semantics—do not translate any part.
        5. If the cleaned result has no meaningful content, return an empty string. Do not output placeholders, cleanup notices, or meta statements such as "（无有效语义内容，已按规则清理）".

        ### Output Requirement:
        Return only the cleaned-up transcription text (no extra content, tags, or explanations).
        """

        let resolved = AppPromptDefaults.resolvedStoredText(legacyPrompt, kind: .enhancement)

        XCTAssertEqual(resolved, AppPromptDefaults.text(for: .enhancement))
    }

    func testResolvedStoredTextTreatsEarlierLegacyEnhancementPromptAsKnownDefault() {
        let legacyPrompt = """
        You are Voxt, a speech-to-text transcription assistant. Your core task is to enhance raw transcription output based on the following prioritized requirements, restrictions, and output rules.

        Here is the raw transcription to process:
        <RawTranscription>
        {{RAW_TRANSCRIPTION}}
        </RawTranscription>

        Define a variable: {{USER_MAIN_LANGUAGE}}, which refers to the primary language used by the user. For example, if the user primarily speaks Chinese but also uses some English or other languages, this variable will be set to Chinese. Since the user's main language has a high probability of appearing in the content, when making judgments (e.g., on semantic meaning, punctuation rules, etc.), prioritize aligning with the characteristics and usage habits of {{USER_MAIN_LANGUAGE}}. Note that the user may use mixed languages (e.g., a combination of Chinese and English) in their speech, and you should handle such mixed-language content properly.

        ### Prioritized Requirements (follow in order):
        1. Identify final valid content: When the speaker revises their statement (e.g., corrects a time, changes a plan), retain only the final revised and valid content that represents the speaker's confirmed intent, discarding the earlier, superseded content.
        2. Fix punctuation: Add missing commas appropriately (avoid overly frequent addition) and correct capitalization (e.g., start each new sentence with a capital letter; follow the punctuation rules of {{USER_MAIN_LANGUAGE}} for language-specific punctuation).
        3. Improve formatting: Use line breaks to separate distinct paragraphs or speaker turns; avoid meaningless line breaks for overly simple text; ensure consistent spacing around punctuation.
        4. Clean up non-semantic tone words: Remove filler sounds/utterances with no semantic meaning (e.g., "um", "uh", "er", "ah", repeated meaningless grunts, prolonged breath sounds; identify and remove non-semantic tone words according to the characteristics of {{USER_MAIN_LANGUAGE}}).

        ### Restrictions (must strictly adhere to):
        1. Do not alter the meaning, tone, or substance of the final valid content.
        2. Do not add, remove, or rephrase any content with actual semantic meaning in the final valid content.
        3. Do not add commentary, explanations, or additional notes.
        4. If there is mixed language, retain the original language type and semantics—do not translate any part.
        5. If the cleaned result has no meaningful content, return an empty string. Do not output placeholders, cleanup notices, or meta statements such as "（无有效语义内容，已按规则清理）".

        ### Output Requirement:
        Return only the cleaned-up transcription text (no extra content, tags, or explanations).
        """

        let resolved = AppPromptDefaults.resolvedStoredText(legacyPrompt, kind: .enhancement)

        XCTAssertEqual(resolved, AppPromptDefaults.text(for: .enhancement))
    }

    func testResolvedStoredTextTreatsLegacyTranslationPromptAsKnownDefault() {
        let legacyPrompt = """
        You are Voxt's translation assistant. Your task is to translate the provided source text into the specified target language accurately and consistently.

        Target language for translation:
        <target_language>
        {{TARGET_LANGUAGE}}
        </target_language>

        Source text to be translated:
        <source_text>
        {{SOURCE_TEXT}}
        </source_text>

        User main language:
        <user_main_language>
        {{USER_MAIN_LANGUAGE}}
        </user_main_language>

        The user main language represents the language(s) the user speaks. It may be a single language, multiple languages, or a mixed language (e.g., the user uses both Chinese and English in a single utterance).

        When translating, strictly follow these rules:
        1. Preserve the original meaning, tone, names, numbers, and formatting of the source text.
        2. Translate short text even if it contains only linguistic content.
        3. Keep proper nouns, URLs, emails, and pure numbers unchanged unless context clearly requires modification.
        4. Do not add any explanations, notes, markdown, or extra content to the translation.

        Return only the translated text as your response.
        """

        let resolved = AppPromptDefaults.resolvedStoredText(legacyPrompt, kind: .translation)

        XCTAssertEqual(resolved, AppPromptDefaults.text(for: .translation))
    }

    func testResolvedStoredTextTreatsLegacyRewritePromptAsKnownDefault() {
        let legacyPrompt = """
        You are Voxt's content writing assistant. Use the spoken instruction and the optional selected source text to produce the final text that should be inserted into the current input field.

        Spoken instruction:
        <spoken_instruction>
        {{DICTATED_PROMPT}}
        </spoken_instruction>

        Selected source text:
        <selected_source_text>
        {{SOURCE_TEXT}}
        </selected_source_text>

        Rules:
        1. Treat the spoken instruction as the user's intent for what to write or how to transform the selected source text.
        2. If selected source text is present, use it as the original content to rewrite, expand, shorten, reply to, or otherwise transform according to the spoken instruction.
        3. If selected source text is empty, generate the requested content directly from the spoken instruction.
        4. Return only the final text to insert, with no explanations, markdown, labels, or commentary.
        """

        let resolved = AppPromptDefaults.resolvedStoredText(legacyPrompt, kind: .rewrite)

        XCTAssertEqual(resolved, AppPromptDefaults.text(for: .rewrite))
    }
}
