#!/usr/bin/env bash

set -euo pipefail

REPORT_PATH=""
ALLOW_UNSIGNED=false
ALLOW_MANUAL_TODOS=false
REQUIRED_LOG_DENYLIST_REGEXES=(
  '(VAD|Silero).*(fatal|Fatal|error|Error)'
  '(fatal|Fatal|error|Error).*(VAD|Silero)'
  '(rawAudio|raw audio|audioSamples|audio samples|sampleBuffer|fullTranscript|full transcript|transcriptText|transcript text|promptText|prompt text|\[VOXT_SMOKE\]\[prompt\])'
)

usage() {
  cat <<'EOF'
Usage: tools/validate_vad_acceptance_report.sh --report PATH [options]

Validates a filled VAD / ASR phase-6 acceptance report. The default mode is a
strict release gate: signed app trust checks must pass, smoke summaries must be
present and clean, every manual scenario row must be explicitly completed, and
completed rows must include evidence or a reason.

Options:
  --report PATH          Required Markdown report generated by
                         tools/create_vad_acceptance_report.sh.
  --allow-unsigned       Do not fail on codesign / spctl failures. Use only for
                         local unsigned package preflight, not release gating.
  --allow-manual-todos   Do not fail on TODO or incomplete manual checklist
                         rows. Use only while drafting a report.
  -h, --help             Show this help.
EOF
}

die() {
  echo "error: $*" >&2
  exit 1
}

record_failure() {
  local message="$1"
  FAILURES+=("$message")
}

report_value() {
  local label="$1"
  awk -v prefix="- $label: " '
    index($0, prefix) == 1 {
      print substr($0, length(prefix) + 1)
      exit
    }
  ' "$REPORT_PATH"
}

is_missing_value() {
  local value="${1:-}"
  [[ -z "$value" || "$value" == "unknown" || "$value" == "not provided" ]]
}

check_smoke_log_artifact() {
  local label="$1"
  local log_path="$2"

  if is_missing_value "$log_path"; then
    record_failure "$label smoke log path is missing"
    return
  fi
  if [[ ! -f "$log_path" ]]; then
    record_failure "$label smoke log file does not exist: $log_path"
    return
  fi
  for required_regex in "${REQUIRED_LOG_DENYLIST_REGEXES[@]}"; do
    if ! grep -F "failOnLogRegex=$required_regex" "$log_path" >/dev/null 2>&1; then
      record_failure "$label smoke log did not enable required denylist: $required_regex"
    fi
  done
  if grep -E 'processExitedBeforeEnd=true|logFailureRegex=' "$log_path" >/dev/null 2>&1; then
    record_failure "$label smoke log contains process exit or denylist failure"
  fi
  if ! grep -E '^pid=[0-9]+' "$log_path" >/dev/null 2>&1; then
    record_failure "$label smoke log is missing pid"
  fi
  if ! grep -E '^durationSeconds=[0-9]+' "$log_path" >/dev/null 2>&1; then
    record_failure "$label smoke log is missing duration"
  fi
  if ! grep -E '^terminated=(term|left-running)$' "$log_path" >/dev/null 2>&1; then
    record_failure "$label smoke log does not show graceful termination or intentional leave-running"
  fi
  if ! awk '/^[[:space:]]*[0-9]+[[:space:]]/ { found=1 } END { exit found ? 0 : 1 }' "$log_path"; then
    record_failure "$label smoke log has no CPU/RSS sample rows"
  fi
}

check_preferences_smoke_summary() {
  local summary_path="$1"

  if is_missing_value "$summary_path"; then
    record_failure "preferences smoke summary path is missing"
    return
  fi
  if [[ ! -f "$summary_path" ]]; then
    record_failure "preferences smoke summary file does not exist: $summary_path"
    return
  fi
  if ! grep -E '^scenario=clean$' "$summary_path" >/dev/null 2>&1; then
    record_failure "preferences smoke summary is missing clean scenario"
  fi
  for required_scenario in local-vad-automatic local-vad-silero local-vad-energy local-vad-off; do
    if ! grep -E "^scenario=$required_scenario$" "$summary_path" >/dev/null 2>&1; then
      record_failure "preferences smoke summary is missing $required_scenario scenario"
    fi
  done
  for required_mode in automatic silero energy off; do
    if ! grep -E "^localVADMode=$required_mode$" "$summary_path" >/dev/null 2>&1; then
      record_failure "preferences smoke summary does not prove localVADMode=$required_mode was preserved"
    fi
  done
  if grep -E '^obsoleteMeetingVADMode=' "$summary_path" >/dev/null 2>&1; then
    record_failure "preferences smoke summary still uses obsolete meetingVADMode evidence"
  fi

  local index=0
  while IFS='=' read -r key value; do
    if [[ "$key" == "smokeLog" ]]; then
      index=$((index + 1))
      check_smoke_log_artifact "preferences-$index" "$value"
    fi
  done < "$summary_path"

  if [[ "$index" -lt 5 ]]; then
    record_failure "preferences smoke summary must include clean and four local VAD mode smoke logs"
  fi
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --report)
      REPORT_PATH="${2:-}"
      [[ -n "$REPORT_PATH" ]] || die "--report requires a value"
      shift 2
      ;;
    --allow-unsigned)
      ALLOW_UNSIGNED=true
      shift
      ;;
    --allow-manual-todos)
      ALLOW_MANUAL_TODOS=true
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

[[ -n "$REPORT_PATH" ]] || die "--report is required"
[[ -f "$REPORT_PATH" ]] || die "report not found: $REPORT_PATH"

FAILURES=()
APP_VALUE="$(report_value "App")"
BUILD_LOG_VALUE="$(report_value "Release build log")"
REGRESSION_LOG_VALUE="$(report_value "Regression matrix log")"
EXECUTABLE_VALUE="$(report_value "Executable")"
EXECUTABLE_SHA256_VALUE="$(report_value "Executable sha256")"
LAUNCH_SMOKE_LOG_VALUE="$(report_value "Launch smoke log")"
DAMAGED_CACHE_SMOKE_LOG_VALUE="$(report_value "Damaged cache smoke log")"
PREFERENCES_SMOKE_SUMMARY_VALUE="$(report_value "Preferences smoke summary")"

if grep -E 'processExitedBeforeEnd=true|logFailureRegex=' "$REPORT_PATH" >/dev/null 2>&1; then
  record_failure "launch smoke or damaged-cache smoke recorded a process exit or denylist match"
fi

check_smoke_log_artifact "launch" "$LAUNCH_SMOKE_LOG_VALUE"
check_smoke_log_artifact "damaged-cache" "$DAMAGED_CACHE_SMOKE_LOG_VALUE"
check_preferences_smoke_summary "$PREFERENCES_SMOKE_SUMMARY_VALUE"

if ! is_missing_value "$BUILD_LOG_VALUE"; then
  if [[ ! -f "$BUILD_LOG_VALUE" ]]; then
    record_failure "release build log file does not exist: $BUILD_LOG_VALUE"
  elif ! grep -F '** BUILD SUCCEEDED **' "$BUILD_LOG_VALUE" >/dev/null 2>&1; then
    record_failure "release build log does not contain BUILD SUCCEEDED: $BUILD_LOG_VALUE"
  fi
fi

if ! is_missing_value "$REGRESSION_LOG_VALUE"; then
  if [[ ! -f "$REGRESSION_LOG_VALUE" ]]; then
    record_failure "regression matrix log file does not exist: $REGRESSION_LOG_VALUE"
  elif ! grep -F '** TEST SUCCEEDED **' "$REGRESSION_LOG_VALUE" >/dev/null 2>&1; then
    record_failure "regression matrix log does not contain TEST SUCCEEDED: $REGRESSION_LOG_VALUE"
  elif grep -E '\*\* TEST FAILED \*\*|Failing tests:|Completed with failures|!! Group failed' "$REGRESSION_LOG_VALUE" >/dev/null 2>&1; then
    record_failure "regression matrix log contains failure markers: $REGRESSION_LOG_VALUE"
  fi
fi

if is_missing_value "$APP_VALUE"; then
  record_failure "app path is missing"
elif [[ ! -d "$APP_VALUE" ]]; then
  record_failure "app bundle does not exist: $APP_VALUE"
fi

if ! grep -E '^- Launch smoke summary: .*denylist=none' "$REPORT_PATH" >/dev/null 2>&1; then
  record_failure "launch smoke summary is missing or denylist is not clean"
fi

if ! grep -E '^- Damaged cache smoke summary: .*denylist=none' "$REPORT_PATH" >/dev/null 2>&1; then
  record_failure "damaged-cache smoke summary is missing or denylist is not clean"
fi

if is_missing_value "$EXECUTABLE_VALUE"; then
  record_failure "executable path is missing"
elif [[ ! -x "$EXECUTABLE_VALUE" ]]; then
  record_failure "executable does not exist or is not executable: $EXECUTABLE_VALUE"
fi

if is_missing_value "$EXECUTABLE_SHA256_VALUE"; then
  record_failure "executable sha256 is missing"
elif [[ -x "$EXECUTABLE_VALUE" ]]; then
  ACTUAL_EXECUTABLE_SHA256="$(shasum -a 256 "$EXECUTABLE_VALUE" | awk '{print $1}')"
  if [[ "$ACTUAL_EXECUTABLE_SHA256" != "$EXECUTABLE_SHA256_VALUE" ]]; then
    record_failure "executable sha256 mismatch: report=$EXECUTABLE_SHA256_VALUE actual=$ACTUAL_EXECUTABLE_SHA256"
  fi
fi

if [[ "$ALLOW_UNSIGNED" != "true" ]]; then
  if [[ -d "$APP_VALUE" ]]; then
    if ! codesign --verify --deep --strict --verbose=2 "$APP_VALUE" >/dev/null 2>&1; then
      record_failure "current app bundle fails codesign verification"
    fi
    if ! spctl --assess --type execute -vv "$APP_VALUE" >/dev/null 2>&1; then
      record_failure "current app bundle fails Gatekeeper spctl assessment"
    fi
  fi
  if grep -E '^codesign --verify: fail' "$REPORT_PATH" >/dev/null 2>&1; then
    record_failure "codesign verification failed"
  fi
  if grep -E '^spctl --assess: fail' "$REPORT_PATH" >/dev/null 2>&1; then
    record_failure "Gatekeeper spctl assessment failed"
  fi
  if ! grep -E '^codesign --verify: pass' "$REPORT_PATH" >/dev/null 2>&1; then
    record_failure "codesign verification pass evidence is missing"
  fi
  if ! grep -E '^spctl --assess: pass' "$REPORT_PATH" >/dev/null 2>&1; then
    record_failure "Gatekeeper spctl pass evidence is missing"
  fi
fi

for required_line in \
  '^- App: ' \
  '^- App version: ' \
  '^- App build: ' \
  '^- Executable: ' \
  '^- Executable sha256: '; do
  if ! grep -E "$required_line" "$REPORT_PATH" | grep -Ev 'unknown|not provided' >/dev/null 2>&1; then
    record_failure "required build identity line is missing or incomplete: $required_line"
  fi
done

if [[ "$ALLOW_MANUAL_TODOS" != "true" ]]; then
  if is_missing_value "$REGRESSION_LOG_VALUE"; then
    record_failure "regression matrix log path is missing"
  fi
  if ! grep -E '^- Regression matrix summary: pass; log=' "$REPORT_PATH" >/dev/null 2>&1; then
    record_failure "regression matrix summary is missing or not pass"
  fi
  if is_missing_value "$BUILD_LOG_VALUE"; then
    record_failure "release build log path is missing"
  fi
  if ! grep -E '^- Release build summary: pass; log=' "$REPORT_PATH" >/dev/null 2>&1; then
    record_failure "release build summary is missing or not pass"
  fi
  if grep -nE '\bTODO\b' "$REPORT_PATH" >/dev/null 2>&1; then
    record_failure "report still contains TODO placeholders"
  fi

  MANUAL_STATUS_FAILURES="$(
    awk -F'|' '
      /^## Manual Scenario Checklist/ { in_table=1; next }
      /^## Blocking Criteria/ { in_table=0 }
      in_table && /^\|/ {
        if ($2 ~ /---/ || $2 ~ /^[[:space:]]*Area[[:space:]]*$/) next
        status=$5
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", status)
        if (status !~ /^(PASS|PASSED|通过|已通过|N\/A|NA)$/) {
          printf "%s:%s\n", NR, $0
        }
      }
    ' "$REPORT_PATH"
  )"
  if [[ -n "$MANUAL_STATUS_FAILURES" ]]; then
    record_failure "manual scenario rows must have Status PASS/PASSED/通过/已通过/N/A/NA"
  fi

  MANUAL_EVIDENCE_FAILURES="$(
    awk -F'|' '
      /^## Manual Scenario Checklist/ { in_table=1; next }
      /^## Blocking Criteria/ { in_table=0 }
      in_table && /^\|/ {
        if ($2 ~ /---/ || $2 ~ /^[[:space:]]*Area[[:space:]]*$/) next
        status=$5
        evidence=$6
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", status)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", evidence)
        if (status ~ /^(PASS|PASSED|通过|已通过|N\/A|NA)$/ && evidence == "") {
          printf "%s:%s\n", NR, $0
        }
      }
    ' "$REPORT_PATH"
  )"
  if [[ -n "$MANUAL_EVIDENCE_FAILURES" ]]; then
    record_failure "manual scenario rows marked PASS/PASSED/通过/已通过/N/A/NA must include evidence or a reason"
  fi
fi

if [[ "${#FAILURES[@]}" -gt 0 ]]; then
  echo "VAD acceptance report validation failed:"
  for failure in "${FAILURES[@]}"; do
    echo "- $failure"
  done
  if [[ -n "${MANUAL_STATUS_FAILURES:-}" ]]; then
    echo
    echo "Incomplete manual rows:"
    echo "$MANUAL_STATUS_FAILURES"
  fi
  if [[ -n "${MANUAL_EVIDENCE_FAILURES:-}" ]]; then
    echo
    echo "Manual rows missing evidence:"
    echo "$MANUAL_EVIDENCE_FAILURES"
  fi
  exit 1
fi

echo "VAD acceptance report validation passed: $REPORT_PATH"
